# Generated by Django 3.1.7 on 2021-03-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210325_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles_list', to='blog.Category'),
        ),
    ]
