# Generated by Django 3.1.7 on 2021-03-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
